const i18nextConfig = {
  lng: navigator.language || navigator.userLanguage, //def:set cl lang,cn for test
  fallbackLng: 'en',
  debug: false,
  resources: {
    zh: {
      translation: {
        "title": "PSBT构造器",
        "warningHeader": "使用前须完全理解比特币UTXO机制（动用总额-转账金额=手续费），否则将造成巨额手续费乌龙！！！",
        "networkLabel": "网络：",
        "inputAddressLabel": "输入地址（每行1个，构造RBF时可为空）：",
        "placeholderAddressPerLine": "每行一个地址",
        "forceRbfLabel": "构造RBF替换交易",
        "forceRbfTitle": "勾选此项并输入因手续费过低尚未确认的交易TXID",
        "fetchUtxoBtn": "查询 UTXO",
        "fetching": "查询中...",
        "tableHeaderUse": "动用",
        "tableHeaderTime": "确认时间及区块",
        "tableHeaderAmount": "金额",
        "tableHeaderTxid": "TXID及序号",
        "tableHeaderAddress": "地址",
        "unconfirmed": "未确认",
        "totalInputAmount": "动用总额：",
        "countLabel": "个数：",
        "targetOutputLabel": "目标输出：",
        "placeholderTargetAddress": "目标地址",
        "placeholderAmountSat": "金额",
        "deleteBtn": "删除",
        "addOutputBtn": "+ 添加输出",
        "totalOutputAmount": "输出总额：",
        "txSizeAndFee": "交易大小：{{vb}}vb 预计费用： {{feeAmount}}(费率{{feeRate}}{{satUnit}}/vb)，内存池最低费率{{minFeeRate}} {{satUnit}}/vb，最低参考费用{{minFee}}",
        "generatePsbtBtn": "生成未签名脚本PSBT",
        "generatePsbtBtnHighFee": "费用过高，我要一意孤行生成并承担{{feeAmount}}聪手续费！！！",
        "generating": "生成中...",
        "psbtHexLabel": "PSBT Base64：",
        "placeholderPsbtHex": "生成后显示",
        "txPreviewLink": "交易预览",
        "broadcastTxLink": "广播交易",
        "status_utxoFound": "完成。共找到 {{count}} 个 UTXO。",
        "status_fetchingTx": "正在获取交易详情: {{txid}}...",
        "build_success": "PSBT 生成完成。可复制 hex 进行后续签名/广播。",
        "error_prefix": "错误：",
        "error_atLeastOneAddress": "请填写至少一个地址",
        "error_noUtxoSelected": "请先选择UTXO",
        "error_noValidOutput": "请添加至少一个有效输出",
        "error_inputLteOutput": "输入总额必须大于输出总额",
        "langLabel": "语言：",
        "txVsize": "预览未签名交易",
        "tx": "交易",
        "preview": "预览",
        "mempool": "内存池",
        "size": "长度",
        "est": "预计",
        "fee": "费用",
        "feeRate": "费率",
        "min": "最低",
        "placeholderRBF": "要替换的原交易TXID，每行1个",
        "note": "广播交易前务必在线上核查交易！ 希望此工具能帮你节省费用，感谢您的比特币捐赠"
      }
    },
    en: {
      translation: {
        "title": "PSBT Builder",
        "warningHeader": "Before using, fully understand the Bitcoin UTXO mechanism (Total Input - Output = Fee), or you may incur a huge mistaken fee!!!",
        "networkLabel": "Network:",
        "inputAddressLabel": "Input addresses (one per line, can be empty for RBF):",
        "placeholderAddressPerLine": "One address per line",
        "forceRbfLabel": "Construct RBF replacement transaction",
        "forceRbfTitle": "Check this and enter the TXID of the unconfirmed transaction due to low fee",
        "fetchUtxoBtn": "Fetch UTXO",
        "fetching": "Fetching...",
        "tableHeaderUse": "Use",
        "tableHeaderTime": "Confirmation Time & Block",
        "tableHeaderAmount": "Amount",
        "tableHeaderTxid": "TXID & Index",
        "tableHeaderAddress": "Address",
        "unconfirmed": "Unconfirmed",
        "totalInputAmount": "Total Input:",
        "countLabel": "Count:",
        "targetOutputLabel": "Target Output:",
        "placeholderTargetAddress": "Target address",
        "placeholderAmountSat": "Amount",
        "deleteBtn": "Delete",
        "addOutputBtn": "+ Add Output",
        "totalOutputAmount": "Total Output:",
        "txSizeAndFee": "Tx size: {{vb}}vb Estimated Fee: {{feeAmount}} (Rate {{feeRate}}{{satUnit}}/vb), Mempool Min Rate {{minFeeRate}} {{satUnit}}/vb, Min Reference Fee {{minFee}}",
        "generatePsbtBtn": "Generate Unsigned PSBT",
        "generatePsbtBtnHighFee": "High fee! I insist on generating and accepting {{feeAmount}} sats fee!!!",
        "generating": "Generating...",
        "psbtHexLabel": "PSBT Base64:",
        "placeholderPsbtHex": "Shown after generation",
        "txPreviewLink": "Transaction Preview",
        "broadcastTxLink": "Broadcast Transaction",
        "status_utxoFound": "Done. Found {{count}} UTXOs.",
        "status_fetchingTx": "Fetching transaction details: {{txid}}...",
        "build_success": "PSBT generated. You can copy the hex for signing/broadcasting.",
        "error_prefix": "Error:",
        "error_atLeastOneAddress": "Please enter at least one address",
        "error_noUtxoSelected": "Please select UTXO first",
        "error_noValidOutput": "Please add at least one valid output",
        "error_inputLteOutput": "Total input must be greater than total output",
        "langLabel": "Language:",
        "txVsize": "Preview Unsigned Transaction",
        "tx": "Transaction",
        "preview": "Preview",
        "mempool": "Mempool",
        "size": "Size",
        "est": "Estimated",
        "fee": "Fee",
        "feeRate": "Fee Rate",
        "min": "Minimum",
        "placeholderRBF": "TXID to replace, one per line",
        "note": "Always verify the transaction online before broadcasting! Hope this tool helps you save fees. Thank you for your Bitcoin donation."
      }
    }
  }
};

// --- i18next 初始化 ---
i18next.init(i18nextConfig);
